In [1]:
import warnings
warnings.simplefilter('ignore')

In [2]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as pt

In [4]:
%matplotlib inline

In [7]:
SR=pd.read_csv('D:/sri/sr.csv')

In [8]:
SR

batting_score wickets runs_conceded catches stumps     opposition  \
0                0       -             -       0      0     v Pakistan   
1                0       -             -       0      0  v New Zealand   
2               36       -             -       0      0  v New Zealand   
3               10       -             -       1      0    v Sri Lanka   
4               20       -             -       0      0     v Pakistan   
..             ...     ...           ...     ...    ...            ...   
458             14       -             -       0      0    v Australia   
459             39       -             -       0      0    v Sri Lanka   
460              6       -             -       1      0    v Sri Lanka   
461            114       -             -       0      0   v Bangladesh   
462             52       0            12       0      0     v Pakistan   

         ground       date  match_result  match_result.1 result_margin toss  \
0    Gujranwala  18-Dec-89           NaN               0        7 runs  won   
1       Dunedin  01-Mar-90           NaN               0      108 runs  won   
2    Wellington  06-Mar-90           NaN               1        1 runs  won   
3       Sharjah  25-Apr-90           NaN               0     3 wickets    0   
4       Sharjah  27-Apr-90           NaN               0       26 runs  won   
..          ...        ...           ...             ...           ...  ...   
458      Sydney  26-Feb-12           NaN               0       87 runs    0   
459      Hobart  28-Feb-12           NaN               1     7 wickets  won   
460       Dhaka  13-Mar-12           NaN               1       50 runs    0   
461       Dhaka  16-Mar-12           NaN               0     5 wickets    0   
462       Dhaka  18-Mar-12           NaN               1     6 wickets    0   

    batting_innings  
0               2nd  
1               2nd  
2               1st  
3               1st  
4               2nd  
..              ...  
458             2nd  
459             2nd  
460             1st  
461             1st  
462             2nd  

[463 rows x 13 columns]

In [9]:
SR.shape

(463, 13)

In [10]:
SR.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   batting_score    463 non-null    int64  
 1   wickets          463 non-null    object 
 2   runs_conceded    463 non-null    object 
 3   catches          463 non-null    object 
 4   stumps           463 non-null    object 
 5   opposition       463 non-null    object 
 6   ground           463 non-null    object 
 7   date             463 non-null    object 
 8   match_result     0 non-null      float64
 9   match_result.1   463 non-null    int64  
 10  result_margin    462 non-null    object 
 11  toss             463 non-null    object 
 12  batting_innings  463 non-null    object 
dtypes: float64(1), int64(2), object(10)
memory usage: 47.1+ KB


In [11]:
nd=SR.drop(['wickets','runs_conceded','catches','stumps','opposition','ground','date','match_result','result_margin','toss','batting_innings'],axis=1)

In [12]:
nd

batting_score  match_result.1
0                0               0
1                0               0
2               36               1
3               10               0
4               20               0
..             ...             ...
458             14               0
459             39               1
460              6               1
461            114               0
462             52               1

[463 rows x 2 columns]

In [13]:
x=nd.iloc[:,0].values.reshape(-1,1)
y=nd.iloc[:,1].values.reshape(-1,1)

In [14]:
x

array([[  0],
       [  0],
       [ 36],
       [ 10],
       [ 20],
       [ 19],
       [ 31],
       [ 36],
       [ 53],
       [ 30],
       [ 31],
       [  4],
       [ 53],
       [ 12],
       [ 22],
       [ 33],
       [ 49],
       [  0],
       [ 62],
       [  4],
       [  1],
       [  1],
       [ 36],
       [ 57],
       [ 48],
       [ 21],
       [ 77],
       [ 31],
       [ 33],
       [  4],
       [ 69],
       [ 35],
       [ 44],
       [ 11],
       [ 34],
       [ 81],
       [  4],
       [ 84],
       [ 14],
       [ 39],
       [ 15],
       [ 10],
       [ 22],
       [ 21],
       [ 32],
       [ 23],
       [ 21],
       [ 55],
       [  1],
       [  3],
       [ 24],
       [  5],
       [ 34],
       [  3],
       [ 44],
       [ 44],
       [ 21],
       [ 15],
       [ 25],
       [ 44],
       [  2],
       [ 24],
       [  3],
       [ 15],
       [ 44],
       [  1],
       [ 45],
       [ 52],
       [ 15],
       [ 82],
       [ 63],
      

In [15]:
y

array([[0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [2],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [4],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [2],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [3],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
    

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,train_size=0.7,random_state=0)

In [18]:
X_test.shape

(139, 1)

In [19]:
from sklearn.linear_model import  LinearRegression

In [20]:
lm=LinearRegression()

In [22]:
lm.fit(X_train,Y_train)

LinearRegression()

In [23]:
y_prediction=lm.predict(X_test)

In [24]:
y_prediction

array([[0.87768427],
       [0.57176201],
       [0.85676651],
       [0.57176201],
       [0.7129569 ],
       [0.7129569 ],
       [0.56914729],
       [0.6737361 ],
       [0.60313865],
       [0.61882697],
       [0.57437673],
       [0.7391041 ],
       [0.77309546],
       [0.64758889],
       [0.63974473],
       [0.81754571],
       [0.80185739],
       [0.70772746],
       [0.70511274],
       [0.59006505],
       [0.57699145],
       [0.66850665],
       [0.57437673],
       [0.65020361],
       [0.56914729],
       [0.60052393],
       [0.65020361],
       [0.65543305],
       [0.58483561],
       [0.58483561],
       [0.7391041 ],
       [0.7129569 ],
       [0.58745033],
       [0.56914729],
       [0.56914729],
       [0.65281833],
       [0.63974473],
       [0.57960617],
       [0.67112138],
       [0.68419498],
       [0.7913985 ],
       [0.67112138],
       [0.89075787],
       [0.6998833 ],
       [0.68419498],
       [0.57176201],
       [0.66589193],
       [0.890

In [25]:
COMP=pd.DataFrame(X_test,columns=['batting_score'])

In [26]:
COMP

batting_score
0              118
1                1
2              110
3                1
4               55
..             ...
134             37
135             68
136            120
137             10
138              7

[139 rows x 1 columns]

In [27]:
COMP['match_result.1']=Y_test

In [28]:
COMP

batting_score  match_result.1
0              118               1
1                1               2
2              110               1
3                1               0
4               55               1
..             ...             ...
134             37               1
135             68               1
136            120               1
137             10               0
138              7               0

[139 rows x 2 columns]

In [29]:
COMP['SRI']=y_prediction

In [31]:
COMP

batting_score  match_result.1       SRI
0              118               1  0.877684
1                1               2  0.571762
2              110               1  0.856767
3                1               0  0.571762
4               55               1  0.712957
..             ...             ...       ...
134             37               1  0.665892
135             68               1  0.746948
136            120               1  0.882914
137             10               0  0.595294
138              7               0  0.587450

[139 rows x 3 columns]

In [32]:
COMP['SRI1']=Y_test

In [33]:
COMP


batting_score  match_result.1       SRI  SRI1
0              118               1  0.877684     1
1                1               2  0.571762     2
2              110               1  0.856767     1
3                1               0  0.571762     0
4               55               1  0.712957     1
..             ...             ...       ...   ...
134             37               1  0.665892     1
135             68               1  0.746948     1
136            120               1  0.882914     1
137             10               0  0.595294     0
138              7               0  0.587450     0

[139 rows x 4 columns]